/*
 * Copyright (C) 2025, Gobierno de España This program is licensed and may be used, modified and
 * redistributed under the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European Commission. Unless
 * required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */


package es.mpt.dsic.loadTables.service.oficinas.model;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by Apache CXF 3.0.16 2021-11-05T11:28:45.699+01:00 Generated source
 * version: 3.0.16
 * 
 */
public final class SD02OFDescargaOficinas_SD02OFDescargaOficinas_Client {

  private static final QName SERVICE_NAME =
      new QName("http://impl.manager.directorio.map.es", "SD02OF_DescargaOficinasService");

  private SD02OFDescargaOficinas_SD02OFDescargaOficinas_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    Log logger = LogFactory.getLog(SD02OFDescargaOficinas_SD02OFDescargaOficinas_Client.class);
    URL wsdlURL = SD02OFDescargaOficinasService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        logger.error(e.getMessage(), e);
      }
    }

    SD02OFDescargaOficinasService ss = new SD02OFDescargaOficinasService(wsdlURL, SERVICE_NAME);
    SD02OFDescargaOficinas port = ss.getSD02OFDescargaOficinas();

    {
      System.out.println("Invoking exportarV2...");
      es.mpt.dsic.loadTables.service.oficinas.model.OficinasWs _exportarV2_oficinasRequest = null;
      es.mpt.dsic.loadTables.service.oficinas.model.RespuestaWS _exportarV2__return =
          port.exportarV2(_exportarV2_oficinasRequest);
      System.out.println("exportarV2.result=" + _exportarV2__return);


    }
    {
      System.out.println("Invoking exportar...");
      es.mpt.dsic.loadTables.service.oficinas.model.OficinasWs _exportar_oficinasRequest = null;
      es.mpt.dsic.loadTables.service.oficinas.model.RespuestaWS _exportar__return =
          port.exportar(_exportar_oficinasRequest);
      System.out.println("exportar.result=" + _exportar__return);


    }
    {
      System.out.println("Invoking exportarV4...");
      es.mpt.dsic.loadTables.service.oficinas.model.OficinasVersionWs _exportarV4_oficinasRequest =
          null;
      es.mpt.dsic.loadTables.service.oficinas.model.RespuestaWS _exportarV4__return =
          port.exportarV4(_exportarV4_oficinasRequest);
      System.out.println("exportarV4.result=" + _exportarV4__return);


    }
    {
      System.out.println("Invoking exportarV3...");
      es.mpt.dsic.loadTables.service.oficinas.model.OficinasWs _exportarV3_oficinasRequest = null;
      es.mpt.dsic.loadTables.service.oficinas.model.RespuestaWS _exportarV3__return =
          port.exportarV3(_exportarV3_oficinasRequest);
      System.out.println("exportarV3.result=" + _exportarV3__return);


    }

    System.exit(0);
  }

}
