/*
 * Copyright (C) 2025, Gobierno de España This program is licensed and may be used, modified and
 * redistributed under the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European Commission. Unless
 * required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.loadTables.service.oficinas.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.16 2021-11-05T11:28:45.829+01:00 Generated source
 * version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://impl.manager.directorio.map.es",
    name = "SD02OF_DescargaOficinas")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SD02OFDescargaOficinas {

  @WebMethod
  @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es",
      partName = "exportarReturn")
  public RespuestaWS exportarV2(
      @WebParam(partName = "oficinasRequest", name = "oficinasRequest") OficinasWs oficinasRequest);

  @WebMethod
  @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es",
      partName = "exportarReturn")
  public RespuestaWS exportar(
      @WebParam(partName = "oficinasRequest", name = "oficinasRequest") OficinasWs oficinasRequest);

  @WebMethod
  @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es",
      partName = "exportarReturn")
  public RespuestaWS exportarV4(@WebParam(partName = "oficinasRequest",
      name = "oficinasRequest") OficinasVersionWs oficinasRequest);

  @WebMethod
  @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es",
      partName = "exportarReturn")
  public RespuestaWS exportarV3(
      @WebParam(partName = "oficinasRequest", name = "oficinasRequest") OficinasWs oficinasRequest);
}
