/*
 * Copyright (C) 2025, Gobierno de España This program is licensed and may be used, modified and
 * redistributed under the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European Commission. Unless
 * required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */


package afirmaws.services.dss.oasis.names.tc.dss._1_0.core.schema;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2 2012-07-12T09:07:32.322+02:00 Generated source
 * version: 2.4.2
 * 
 */
public final class DSSSignatureDSSAfirmaVerifyClient {

  private static final QName SERVICE_NAME =
      new QName("urn:oasis:names:tc:dss:1.0:core:schema", "DSSSignatureService");

  private DSSSignatureDSSAfirmaVerifyClient() {}

  public static void main(String[] args) throws java.lang.Exception {

    Logger logger = Logger.getLogger(DSSSignatureDSSAfirmaVerifyClient.class.getName());
    URL wsdlURL = DSSSignatureService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        logger.severe(e.getMessage());
      }
    }

    DSSSignatureService ss = new DSSSignatureService(wsdlURL, SERVICE_NAME);
    DSSSignature port = ss.getDSSAfirmaVerify();

    {
      logger.info("Invoking verify...");
      java.lang.String verifydssXML = "";
      java.lang.String verify_return = port.verify(verifydssXML);
      logger.info("verify.result=" + verify_return);


    }

    System.exit(0);
  }

}
