# Original (see): https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from master branch only.

variables:
#  SONAR_PROJECT_KEY: "es.gob.aapp.eeutil:eeutil-util"
  SONAR_PROJECT_KEY: "${CI_PROJECT_PATH_SLUG}"
  SONAR_PROJECT_NAME: "eeutil-util"
  SONAR_TOKEN: "8d503a6b92224622dba1c1262c2627ef57852376"
  SONAR_URL: "https://sonarqube-ic.scae.redsara.es/sonar"
#  MAVEN_CLI_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dhttps.protocols=TLSv1.2 --batch-mode --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dhttps.protocols=TLSv1.2 --batch-mode --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"  
  SONAR_SCANNER_OPTS: "-Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName=${SONAR_PROJECT_NAME} -Dsonar.qualitygate.wait=true -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html -Dsonar.sourceEncoding=ISO-8859-1 -Djavax.net.ssl.trustStore=ci-truststore.ks -Djavax.net.ssl.keyStore=ci-truststore.ks -Djavax.net.ssl.trustStorePassword=otpsgad"
  MAVEN_SONAR_OPTS: "-Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName=${SONAR_PROJECT_NAME} -Dsonar.qualitygate.wait=true -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_URL} -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.java.binaries=**/* -Dsonar.sourceEncoding=ISO-8859-1 -Djavax.net.ssl.trustStore=ci-truststore.ks -Djavax.net.ssl.keyStore=ci-truststore.ks -Djavax.net.ssl.trustStorePassword=otpsgad"

# * This template uses jdk8 for verifying and deploying images.
# * OTP: Imagen adaptada para SGAD.

image: artefactos-ic.scae.redsara.es:6001/maven-sgad:3.3.9-jdk-8


stages:
  - deploy
  - test

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


# To deploy packages from CI, create a ci_settings.xml file
# For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for more details.
# Please note: The GitLab Maven Repository is currently only available in GitLab Premium / Ultimate.
# For `master` branch run `mvn deploy` automatically.
deploy:jdk8:
  stage: deploy
  script:
# echo 'Variables de entorno'  
# printenv
# echo ${MAVEN_CLI_OPTS} 
# OTP: TODO: Cambiar de install a deploy cuando se estandarice y configure nexus como destino
    - 'mvn $MAVEN_CLI_OPTS clean deploy -e -X -PredSara -s ci_settings.xml'
  only:
    - feature-2405
    
    
.sonar: &sonar
  stage: test
  allow_failure: true
  script:
    - echo $MAVEN_SONAR_OPTS
#    - 'mvn $MAVEN_CLI_OPTS $MAVEN_SONAR_OPTS sonar:sonar'
    - mvn $MAVEN_CLI_OPTS compile org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -Psonar -Dsonar.projectKey=es.gob.aapp.eeutil:eeutil-util -Dsonar.host.url=https://sonarqube-ic.scae.redsara.es/sonar -Dsonar.login=8d503a6b92224622dba1c1262c2627ef57852376
  only:
    - feature-2405   
    
sonar:
  <<: *sonar
     
    
    


    

