/*
 * Copyright (C) 2025, Gobierno de España This program is licensed and may be used, modified and
 * redistributed under the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European Commission. Unless
 * required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */


package es.mpt.dsic.loadTables.service.model;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by Apache CXF 3.0.16 2021-11-05T11:28:39.726+01:00 Generated source
 * version: 3.0.16
 * 
 */
public final class SD01UNDescargaUnidades_SD01UNDescargaUnidades_Client {

  private static final QName SERVICE_NAME =
      new QName("http://impl.manager.directorio.map.es", "SD01UN_DescargaUnidadesService");


  private SD01UNDescargaUnidades_SD01UNDescargaUnidades_Client() {}

  public static void main(String args[]) throws java.lang.Exception {

    Log logger = LogFactory.getLog(SD01UNDescargaUnidades_SD01UNDescargaUnidades_Client.class);
    URL wsdlURL = SD01UNDescargaUnidadesService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        logger.error(e.getMessage(), e);
      }
    }

    SD01UNDescargaUnidadesService ss = new SD01UNDescargaUnidadesService(wsdlURL, SERVICE_NAME);
    SD01UNDescargaUnidades port = ss.getSD01UNDescargaUnidades();

    {
      System.out.println("Invoking exportarV2...");
      es.mpt.dsic.loadTables.service.model.UnidadesWs _exportarV2_unidadesRequest = null;
      es.mpt.dsic.loadTables.service.model.RespuestaWS _exportarV2__return =
          port.exportarV2(_exportarV2_unidadesRequest);
      System.out.println("exportarV2.result=" + _exportarV2__return);


    }
    {
      System.out.println("Invoking exportar...");
      es.mpt.dsic.loadTables.service.model.UnidadesWs _exportar_unidadesRequest = null;
      es.mpt.dsic.loadTables.service.model.RespuestaWS _exportar__return =
          port.exportar(_exportar_unidadesRequest);
      System.out.println("exportar.result=" + _exportar__return);


    }
    {
      System.out.println("Invoking exportarV3...");
      es.mpt.dsic.loadTables.service.model.UnidadesWsVersion _exportarV3_unidadesRequest = null;
      es.mpt.dsic.loadTables.service.model.RespuestaWS _exportarV3__return =
          port.exportarV3(_exportarV3_unidadesRequest);
      System.out.println("exportarV3.result=" + _exportarV3__return);


    }

    System.exit(0);
  }

}
